// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID           int64
	UserID       int64
	SessionToken string
	CreatedAt    sql.NullTime
	ExpiresAt    time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	Ip           string
	Role         string
	CreatedAt    sql.NullTime
}
