// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countUsersByIP = `-- name: CountUsersByIP :one
SELECT COUNT(*) FROM users
WHERE ip = ?
`

func (q *Queries) CountUsersByIP(ctx context.Context, ip string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByIP, ip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, session_token, created_at, expires_at)
VALUES (?, ?, datetime('now'), ?)
RETURNING id, user_id, session_token, created_at, expires_at
`

type CreateSessionParams struct {
	UserID       int64
	SessionToken string
	ExpiresAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.SessionToken, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, created_at)
VALUES (?, ?, datetime('now'))
RETURNING id, username, password_hash, created_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

type CreateUserRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createUserWithIP = `-- name: CreateUserWithIP :one
INSERT INTO users (username, password_hash, ip, created_at)
VALUES (?, ?, ?, datetime('now'))
RETURNING id, username, password_hash, created_at
`

type CreateUserWithIPParams struct {
	Username     string
	PasswordHash string
	Ip           string
}

type CreateUserWithIPRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

func (q *Queries) CreateUserWithIP(ctx context.Context, arg CreateUserWithIPParams) (CreateUserWithIPRow, error) {
	row := q.db.QueryRowContext(ctx, createUserWithIP, arg.Username, arg.PasswordHash, arg.Ip)
	var i CreateUserWithIPRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createUserWithRole = `-- name: CreateUserWithRole :one
INSERT INTO users (username, password_hash, ip, role, created_at)
VALUES (?, ?, ?, ?, datetime('now'))
RETURNING id, username, password_hash, ip, role, created_at
`

type CreateUserWithRoleParams struct {
	Username     string
	PasswordHash string
	Ip           string
	Role         string
}

func (q *Queries) CreateUserWithRole(ctx context.Context, arg CreateUserWithRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithRole,
		arg.Username,
		arg.PasswordHash,
		arg.Ip,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Ip,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE session_token = ?
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, sessionToken)
	return err
}

const deleteUserByUsername = `-- name: DeleteUserByUsername :exec
DELETE FROM users
WHERE username = ?
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUsername, username)
	return err
}

const deleteUsersByPrefix = `-- name: DeleteUsersByPrefix :exec
DELETE FROM users
WHERE username LIKE ?
`

// supply prefix like 'test_' (we append '%' in code, but you can also pass prefix||'%')
func (q *Queries) DeleteUsersByPrefix(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUsersByPrefix, username)
	return err
}

const deleteUsersCreatedBetween = `-- name: DeleteUsersCreatedBetween :exec
DELETE FROM users
WHERE created_at >= ?1 AND created_at < ?2
`

type DeleteUsersCreatedBetweenParams struct {
	Start sql.NullTime
	End   sql.NullTime
}

// Delete users created_at >= start AND created_at < end
// param start: timestamp
// param end: timestamp
func (q *Queries) DeleteUsersCreatedBetween(ctx context.Context, arg DeleteUsersCreatedBetweenParams) error {
	_, err := q.db.ExecContext(ctx, deleteUsersCreatedBetween, arg.Start, arg.End)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, session_token, created_at, expires_at
FROM sessions
WHERE session_token = ?
LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, sessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at
FROM users
WHERE id = ?
LIMIT 1
`

type GetUserByIDRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at
FROM users
WHERE username = ?
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserFullByUsername = `-- name: GetUserFullByUsername :one
SELECT id, username, password_hash, ip, role, created_at
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetUserFullByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFullByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Ip,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, ip, role, created_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Ip,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPatch = `-- name: UpdateUserPatch :one
UPDATE users SET
    password_hash = COALESCE(?, password_hash),
    ip            = COALESCE(?, ip),
    role          = COALESCE(?, role)
WHERE username = ?
RETURNING id, username, password_hash, ip, role, created_at
`

type UpdateUserPatchParams struct {
	PasswordHash string
	Ip           string
	Role         string
	Username     string
}

// Update any subset of password_hash/ip/role. Supply NULL to leave value unchanged.
func (q *Queries) UpdateUserPatch(ctx context.Context, arg UpdateUserPatchParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPatch,
		arg.PasswordHash,
		arg.Ip,
		arg.Role,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Ip,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
